// Code generated by dagger-compiler.  Do not edit.
package com.nuvyyo.android.slipstream.exovideoplayer;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AppModule$$ModuleAdapter extends ModuleAdapter<AppModule> {
  private static final String[] INJECTS = { "members/com.nuvyyo.android.slipstream.exovideoplayer.TabloPlayer", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public AppModule$$ModuleAdapter() {
    super(com.nuvyyo.android.slipstream.exovideoplayer.AppModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, false /*complete*/, true /*library*/);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, AppModule module) {
    bindings.contributeProvidesBinding("@javax.inject.Named(value=CAST_APP_ID)/java.lang.String", new CAST_APP_IDProvidesAdapter(module));
    bindings.contributeProvidesBinding("com.nuvyyo.android.slipstream.exovideoplayer.MediaSessionDetails", new ProvideMediaSessionDetailsProvidesAdapter(module));
    bindings.contributeProvidesBinding("com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer", new ProvideBasePlayerProvidesAdapter(module));
    bindings.contributeProvidesBinding("@javax.inject.Named(value=USER_AGENT)/java.lang.String", new USER_AGENTProvidesAdapter(module));
  }

  /**
   * A {@code Binding<java.lang.String>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<java.lang.String>} and handling creation and
   * preparation of object instances.
   */
  public static final class CAST_APP_IDProvidesAdapter extends ProvidesBinding<String>
      implements Provider<String> {
    private final AppModule module;

    public CAST_APP_IDProvidesAdapter(AppModule module) {
      super("@javax.inject.Named(value=CAST_APP_ID)/java.lang.String", NOT_SINGLETON, "com.nuvyyo.android.slipstream.exovideoplayer.AppModule", "CAST_APP_ID");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<java.lang.String>}.
     */
    @Override
    public String get() {
      return module.CAST_APP_ID();
    }
  }

  /**
   * A {@code Binding<com.nuvyyo.android.slipstream.exovideoplayer.MediaSessionDetails>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<com.nuvyyo.android.slipstream.exovideoplayer.MediaSessionDetails>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideMediaSessionDetailsProvidesAdapter extends ProvidesBinding<MediaSessionDetails>
      implements Provider<MediaSessionDetails> {
    private final AppModule module;

    public ProvideMediaSessionDetailsProvidesAdapter(AppModule module) {
      super("com.nuvyyo.android.slipstream.exovideoplayer.MediaSessionDetails", IS_SINGLETON, "com.nuvyyo.android.slipstream.exovideoplayer.AppModule", "provideMediaSessionDetails");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<com.nuvyyo.android.slipstream.exovideoplayer.MediaSessionDetails>}.
     */
    @Override
    public MediaSessionDetails get() {
      return module.provideMediaSessionDetails();
    }
  }

  /**
   * A {@code Binding<com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideBasePlayerProvidesAdapter extends ProvidesBinding<com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer>
      implements Provider<com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer> {
    private final AppModule module;

    public ProvideBasePlayerProvidesAdapter(AppModule module) {
      super("com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer", NOT_SINGLETON, "com.nuvyyo.android.slipstream.exovideoplayer.AppModule", "provideBasePlayer");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer>}.
     */
    @Override
    public com.nuvyyo.android.slipstream.exovideoplayer.player.ExoPlayer get() {
      return module.provideBasePlayer();
    }
  }

  /**
   * A {@code Binding<java.lang.String>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<java.lang.String>} and handling creation and
   * preparation of object instances.
   */
  public static final class USER_AGENTProvidesAdapter extends ProvidesBinding<String>
      implements Provider<String> {
    private final AppModule module;

    public USER_AGENTProvidesAdapter(AppModule module) {
      super("@javax.inject.Named(value=USER_AGENT)/java.lang.String", IS_SINGLETON, "com.nuvyyo.android.slipstream.exovideoplayer.AppModule", "USER_AGENT");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<java.lang.String>}.
     */
    @Override
    public String get() {
      return module.USER_AGENT();
    }
  }
}
